version: "3.8"

services: 

#Nginx Service
webserver:
    image:  nginx:stable-alpine
    container_name: lcp_nginx
    restart: unless-stopped
    ports: 
        - "8080:80"
    volumes:
        - .:/var/www/html
        - ./laraV08admin/default.conf:/etc/nginx/conf.d/default.conf
depends_on: 
        - php
        - mysql
networks: 
        - laraV08admin
        
#MySQL Service
mysql:
    image: mysql:8.0.21
    container_name: lcp_mysql
    restart: unless-stopped
    tty: true
    ports: 
        -"33061:3306"
    environment: 
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes: 
        ./dockerize/mysql/data/
        ./dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
        networks: 
            - laraV08admin
#PHP Service
php:
    build: 
        context: .
        dockerfile: ./dockerize/app/php.dockerfile
    container_name: lcp_php
    volumes: 
        - .:/var/www/html
    ports: 9000:9000
    networks: 
        - laraV08admin


#Composer Service
composer:
    image: composer:latest
    container_name: lcp_composer
    volumes: 
        - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
        - php
    networks: 
        - laraV08admin

#NPM Service
npm:
    image: 
#Artisan Service
artisan:

#Docker Networks
networks: 
    laraV08admin: